site_name: mlquantify




theme: 
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigations.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

  language: en

  palette:

    # Palette toggle for light mode
    - scheme: slate 
      primary: deep purple
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      primary: deep purple
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



plugins:
  - search
  - tags
  - blog
